import { createMetadata } from '@fck/lib/seo/metadata';
import { ArrowLeftIcon } from '@radix-ui/react-icons';
import type { Metadata } from 'next';
import Link from 'next/link';
import Balancer from 'react-wrap-balancer';
import '@fck/styles/globals.css';

export const metadata: Metadata = createMetadata({
  title: 'Privacy Policy – Cloud Context',
  description:
    'Learn how Cloud Context collects, uses, and protects your personal information.',
});

const PrivacyPolicyPage = () => {
  return (
    <div className="container mx-auto max-w-5xl py-16">
      {/* Back navigation */}
      <Link
        href="/"
        className="mb-4 inline-flex items-center gap-1 text-muted-foreground text-sm hover:underline focus:outline-none"
      >
        <ArrowLeftIcon className="h-4 w-4" />
        Back to Home
      </Link>

      {/* Page Title */}
      <h1 className="scroll-m-20 font-extrabold text-4xl tracking-tight lg:text-5xl">
        <Balancer>Privacy Policy</Balancer>
      </h1>

      {/* Page Subtitle */}
      <p className="mt-4 text-lg text-muted-foreground leading-relaxed">
        <Balancer>
          How we collect, use, and protect your data at Cloud Context.
        </Balancer>
      </p>

      {/* Main Content */}
      <div className="mt-12">
        <div className="prose prose-neutral dark:prose-invert max-w-none">
          <h2>1. Introduction</h2>
          <p>
            Welcome to <strong>cloudcontext.cc</strong>. This Privacy Policy
            describes how we handle personal information collected from users of
            the site.
          </p>

          <h2>2. Information We Collect</h2>
          <p>
            We may collect personal information like your name, email address,
            and contact details when you:
          </p>
          <ul>
            <li>Register or log in to the site</li>
            <li>Subscribe to a newsletter</li>
            <li>Submit feedback</li>
          </ul>
          <p>
            We also collect anonymous usage data, including pages visited,
            interactions, and device/browser information, to improve the
            performance and security of the service.
          </p>

          <h2>3. How We Use Your Information</h2>
          <p>Your information helps us to:</p>
          <ul>
            <li>Improve website offerings</li>
            <li>Send periodic emails with updates or information</li>
            <li>Respond to inquiries or customer service requests</li>
          </ul>

          <h2>4. User Identification and Analytics</h2>
          <p>
            We use <strong>Google Analytics</strong> to understand how visitors
            use our website and app. When you log in, we may associate your
            session with a unique user ID (generated by Clerk). This helps us
            measure engagement across sessions and devices without identifying
            you personally.
          </p>
          <p>
            The user ID is a random identifier and does not include personally
            identifiable information such as your name or email address.
          </p>
          <p>
            Learn more:{' '}
            <a
              href="https://policies.google.com/technologies/partner-sites"
              target="_blank"
              rel="noopener noreferrer"
            >
              How Google handles data
            </a>
          </p>
          <p>As part of our privacy-first approach:</p>
          <ul>
            <li>
              You can opt out of Google Analytics using{' '}
              <a
                href="https://tools.google.com/dlpage/gaoptout"
                target="_blank"
                rel="noopener noreferrer"
              >
                Google’s browser add-on
              </a>
            </li>
            <li>
              You may disable cookies in your browser, though it may affect some
              site features
            </li>
          </ul>

          <h2>5. Protection of Information</h2>
          <p>
            We implement security measures to maintain the safety of your
            personal information.
          </p>

          <h2>6. Cookies</h2>
          <p>
            We use cookies to enhance your experience. You can refuse cookies
            via your browser settings.
          </p>

          <h2>7. Sharing Your Information</h2>
          <p>
            We do not sell or rent personal information. We may share limited
            usage data with trusted third-party partners for analytics,
            advertising, or performance monitoring. This data is anonymized and
            cannot identify you.
          </p>

          <h2>8. Third-Party Links</h2>
          <p>
            Our site may contain links to third-party websites. We are not
            responsible for their privacy practices.
          </p>

          <h2>9. Changes to This Policy</h2>
          <p>
            We reserve the right to update this Privacy Policy at any time.
            Changes are effective immediately upon posting on this website.
          </p>

          <h2>10. Contact Us</h2>
          <p>
            For questions about this Privacy Policy, please use the contact form
            or email us at{' '}
            <a href="mailto:mathewlewallen@cloudcontext.cc">
              mathewlewallen@cloudcontext.cc
            </a>
            .
          </p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;
