import "@fck/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from "@fck/components/theme-provider";
import { TRPCReactProvider } from "@fck/server/trpc/react";
import { AuthProvider } from "@fck/server/auth/provider"

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
  })
  
  const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
  })

  export default function RootLayout({
	children,
  }: {
	children: React.ReactNode;
  }) {
	return (
		<html lang="en" suppressHydrationWarning>
		  <body className={`font-sans ${geistSans.variable} ${geistMono.variable} antialiased`}>
			<ThemeProvider
			  attribute="class"
			  defaultTheme="system"
			  enableSystem
			  disableTransitionOnChange
			>
			  <AuthProvider>
				<TRPCReactProvider >
				  {children}
				</TRPCReactProvider>
			  </AuthProvider>
			</ThemeProvider>
		  </body>
		</html>
	  );
	}
	